image:
  file: .gitpod.Dockerfile
tasks:
  - init: ''
    command: 'echo "Start Project deno-livestream: deno run --allow-net --allow-env --allow-read -A --unstable main.ts"'

vscode:
  extensions:
    - denoland.vscode-deno
