image:
  file: .gitpod.Dockerfile
tasks:
  - init: ''
    command: 'echo "Start Project deno-livestream: $ npx node-media-server && deno run --allow-net --allow-env --allow-read -A --unstable --allow-run main.ts"'

vscode:
  extensions:
    - denoland.vscode-deno
